target 'SocialPosts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SocialPosts
  pod 'PINRemoteImage', '~> 3.0.0-beta'
  pod 'Alamofire', '~> 5.0.0-beta.5'
  pod 'SwiftyJSON', '~> 4.0'

  target 'SocialPostsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SocialPostsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
